# Generated by Django 5.2 on 2026-03-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0004_alter_subject_id_topic'),
        ('exams', '0008_remove_question_topic'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
