# Generated by Django 5.2 on 2026-03-14 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='context',
            field=models.TextField(blank=True, help_text='Ngữ cảnh/đoạn dẫn (dùng cho dạng Đúng/Sai hoặc câu hỏi có bối cảnh).', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='correct_answer_text',
            field=models.CharField(blank=True, help_text='Đáp án đúng dạng text (dùng cho dạng Trả lời ngắn).', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('multiple_choice', 'Trắc nghiệm (chọn 1/4)'), ('true_false', 'Đúng / Sai'), ('short_answer', 'Trả lời ngắn')], default='multiple_choice', help_text='Dạng câu hỏi theo format đề thi THPT 2025.', max_length=20),
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='answer_text',
            field=models.CharField(blank=True, help_text='Đáp án text (cho dạng trả lời ngắn).', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='explanation',
            field=models.TextField(blank=True, help_text='Lời giải thích chi tiết cho phương án này.', null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(help_text='Nội dung câu hỏi chính.'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
