# Generated by Django 5.2 on 2026-03-14 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_question_context_question_correct_answer_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Hình ảnh đính kèm (nếu có).', null=True, upload_to='questions/images/'),
        ),
    ]
