# Generated by Django 5.2 on 2026-03-14 10:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_question_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBank',
            fields=[
                ('sha256', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('image_file', models.ImageField(upload_to='questions/images/bank/')),
                ('width_pt', models.FloatField(blank=True, help_text='Độ rộng hiển thị (pt) trong docx gốc', null=True)),
                ('height_pt', models.FloatField(blank=True, help_text='Độ cao hiển thị (pt) trong docx gốc', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='content_json',
            field=models.JSONField(blank=True, help_text='Nội dung phương án dạng blocks (tương tự câu hỏi)', null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='content_json',
            field=models.JSONField(blank=True, help_text="Nội dung câu hỏi dạng blocks [{type: 'text', value: '...'}, {type: 'image', sha256: '...'}]", null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Hình ảnh đính kèm cũ (nếu có).', null=True, upload_to='questions/images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, help_text='Nội dung câu hỏi chính (text thô).', null=True),
        ),
        migrations.CreateModel(
            name='QuestionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(default=0, help_text='Thứ tự xuất hiện')),
                ('placement', models.CharField(default='stem', help_text='Vị trí: stem, choice_A, sub_a...', max_length=50)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exams.imagebank')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_images', to='exams.question')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
