# Generated by Django 6.0.3 on 2026-03-19 14:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0006_question_topic_quiz_publish_at_alter_option_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='imagebank',
            name='file_size',
            field=models.PositiveIntegerField(blank=True, help_text='Dung lượng ảnh theo bytes', null=True),
        ),
        migrations.AddField(
            model_name='imagebank',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='imagebank',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='questionimage',
            name='note',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questionimage',
            name='source_type',
            field=models.CharField(choices=[('ai_scan', 'AI Scan'), ('user_upload', 'User Upload'), ('system', 'System')], default='user_upload', max_length=20),
        ),
        migrations.AddField(
            model_name='questionimage',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_images_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='questionimage',
            unique_together={('question', 'image', 'placement', 'position')},
        ),
    ]
