# Generated by Django 5.2 on 2026-03-20 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0007_imagebank_file_size_imagebank_mime_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='topic',
        ),
    ]
