# Generated by Django 5.2 on 2026-03-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0008_remove_question_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='Lời giải thích chi tiết cho toàn bộ câu hỏi.', null=True),
        ),
    ]
