# Generated by Django 5.2 on 2026-03-25 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0009_question_explanation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='questionimage',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='imagebank',
            name='image_url',
            field=models.URLField(blank=True, help_text='Link ảnh trực tiếp (vd: Cloudinary)', max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='questionimage',
            name='image_url',
            field=models.URLField(blank=True, help_text='Link ảnh trực tiếp từ AI/Cloudinary', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Nhận biết'), ('medium', 'Thông hiểu'), ('hard', 'Vận dụng')], default='easy', max_length=10),
        ),
        migrations.AlterField(
            model_name='questionimage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exams.imagebank'),
        ),
    ]
