# Generated by Django 5.2 on 2026-03-19 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0004_alter_document_id_alter_documentchunk_id'),
        ('classes', '0004_alter_subject_id_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInsight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classroom', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_insight', to='classes.class')),
            ],
        ),
    ]
