# Generated by Django 5.2 on 2026-03-23 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0005_classinsight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
