# Generated by Django 5.2 on 2026-03-25 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_core', '0006_remove_document_file_path_document_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
